### ISSUE TITLE
[All_PopUps] Close Button ? 

### ISSUE THREAD

**Issue by salom210** [bubblesapp/mobile#11]
Why do we display a close Button on the Alert and Contact info Popup? Whereas we do not on the "Add people" one? 

Can we remove the close button to only keep the "close" icon?

![image](https://user-images.githubusercontent.com/45338808/81584013-784d1200-93b2-11ea-9708-2d98345087d6.png)

**Comment by egoossens** [comment]
In my opinion, the "normal" action after viewing an alert is to close it.
