### ISSUE TITLE
[All_MessageBoxes] Color uniformization (red and green)

### ISSUE THREAD

**Issue by salom210** [bubblesapp/mobile#13]
Can we use the Red color and the Green color we use for the Bubble here ?

**Comment by egoossens** [comment]
The red is already the same, but I feel like the green is too light for white text no?

<img width="371" alt="Screenshot 2020-05-12 at 17 18 35" src="https://user-images.githubusercontent.com/1333414/81712330-c296c780-9474-11ea-8e04-efe4c04f2f29.png">
