### ISSUE TITLE
English in the French version 

### ISSUE THREAD

**Issue by laykhe** [bubblesapp/mobile#35]
+ aller à la ligne après 
« Prévenez les bonnes personnes
en cas de risque »
![2E96D131-72C1-4FC6-AB4F-C353AE2D47DA](https://user-images.githubusercontent.com/65240339/81778364-0203f900-94f3-11ea-8443-17ee6a0d3c13.png)

**Comment by egoossens** [comment]
Closing as duplicate of #28
